---
- name: Deploy dotfiles
  hosts: all
  vars:
    target_user: "{{ ansible_env.USER }}"
  roles:
    - role: ansible
    - role: sudo
    - role: ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: yes
    - role: AlmaLinux
      when: ansible_facts['distribution'] == 'AlmaLinux'
      become: yes
    - role: dotfiles
    - role: zsh
    - role: vim
    - role: awscli
